/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/env.d.ts --include-runtime false` (hash: 2a64ffe6a708f27784622d7cb46431d4)
interface __BaseEnv_Env {
	LC_RATING_DATA: KVNamespace;
	ALLOWED_ORIGINS: "https://youyun8.github.io,http://localhost:3001";
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	JWT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
